org: jucada2
service: api-ingesta

provider:
  name: aws
  runtime: python3.12
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    INGEST_BUCKET: ${self:service}-ingesta-${self:provider.stage}
  iam:
    role: arn:aws:iam::395409307624:role/LabRole

resources:
  Resources:
    IngestBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.INGEST_BUCKET}

functions:
  comentario:
    handler: comentario.lambda_handler
    events:
      - http:
          path: /comentario
          method: post
          cors: true
